# Generated by Django 5.2.6 on 2025-09-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_itinerary'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
