# Generated by Django 5.2.6 on 2025-09-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alert_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_altitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
