# Generated by Django 5.2.6 on 2025-09-28 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_customuser_last_altitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('Unassigned', 'Unassigned'), ('Acknowledged', 'Acknowledged'), ('Assigned', 'Assigned'), ('Resolved', 'Resolved')], default='Unassigned', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='location_history',
            field=models.JSONField(default=list),
        ),
    ]
