# Generated by Django 5.2.6 on 2026-03-05 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alert_assigned_to_alert_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaSafetyRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('overall_rating', models.DecimalField(decimal_places=2, default=7.5, max_digits=3)),
                ('crime_rate', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('theft_incidents', models.IntegerField(default=0)),
                ('violent_incidents', models.IntegerField(default=0)),
                ('safe_hours', models.JSONField(default=dict)),
                ('safe_areas', models.TextField(blank=True)),
                ('risky_areas', models.TextField(blank=True)),
                ('user_reports_count', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('service_type', models.CharField(choices=[('Police', 'Police'), ('Ambulance', 'Ambulance'), ('Fire', 'Fire'), ('Embassy', 'Embassy'), ('Tourist Police', 'Tourist Police'), ('Hospital', 'Hospital'), ('Other', 'Other')], max_length=50)),
                ('service_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('alternate_number', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('language', models.CharField(default='English', max_length=50)),
            ],
            options={
                'ordering': ['country', 'city', 'service_type'],
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.JSONField()),
                ('location_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Safe', 'Safe'), ('Moderate Risk', 'Moderate Risk'), ('Need Help', 'Need Help')], default='Safe', max_length=50)),
                ('note', models.TextField(blank=True)),
                ('photo_url', models.URLField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('visibility', models.CharField(choices=[('Public', 'Public'), ('Trusted Circle', 'Trusted Circle'), ('Private', 'Private')], default='Trusted Circle', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
                ('phrase_type', models.CharField(choices=[('Help', 'Help'), ('Police', 'Police'), ('Hospital', 'Hospital'), ('Danger', 'Danger'), ('Safe', 'Safe'), ('Address', 'Address'), ('Water', 'Water'), ('Food', 'Food'), ('Bathroom', 'Bathroom'), ('Thank You', 'Thank You'), ('Yes/No', 'Yes/No')], max_length=50)),
                ('english_text', models.CharField(max_length=255)),
                ('local_text', models.CharField(max_length=255)),
                ('pronunciation', models.CharField(blank=True, max_length=255)),
                ('audio_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['language', 'phrase_type'],
                'unique_together': {('language', 'phrase_type')},
            },
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('Theft', 'Theft'), ('Assault', 'Assault'), ('Scam', 'Scam'), ('Harassment', 'Harassment'), ('Bad Transportation', 'Bad Transportation'), ('Dangerous Area', 'Dangerous Area'), ('Accident', 'Accident'), ('Other', 'Other')], max_length=100)),
                ('location', models.JSONField()),
                ('location_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('photo_url', models.URLField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('helpful_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Pending Review', 'Pending Review'), ('Verified', 'Verified'), ('Under Investigation', 'Under Investigation'), ('Resolved', 'Resolved')], default='Pending Review', max_length=50)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SafeRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_location', models.JSONField()),
                ('end_location', models.JSONField()),
                ('route_name', models.CharField(max_length=200)),
                ('waypoints', models.JSONField(default=list)),
                ('danger_zones', models.JSONField(default=list)),
                ('safety_score', models.IntegerField(default=85)),
                ('distance_km', models.FloatField()),
                ('estimated_time_minutes', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_saved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrustedCircleMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('relationship', models.CharField(default='Family', max_length=50)),
                ('can_see_location', models.BooleanField(default=True)),
                ('can_see_status', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_in_circles', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_circle', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'friend')},
            },
        ),
    ]
