# Generated by Django 5.2.6 on 2026-04-06 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_areasafetyrating_emergencynumber_checkin_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trustedcirclemember',
            unique_together={('user', 'phone_number')},
        ),
        migrations.RemoveField(
            model_name='trustedcirclemember',
            name='friend',
        ),
    ]
